### ISSUE TITLE
ENRs in the "Info" tab not sorted in meaningful order

### ISSUE THREAD

**Issue by czepluch** [dappnode/DAppNodePackage-holesky-obol#21]
**Describe the bug**

In the Holesky Obol package (potentially also the mainnet package) the order of the ENRs in the "Info" tab is weird. For example in my package they're ordered like in the picture below. This can cause confusion when you need to use your ENR during setup of a cluster.
![telegram-cloud-photo-size-4-5884450365317955000-x](https://github.com/dappnode/DAppNodePackage-holesky-obol/assets/1026799/cd39f271-92b1-4574-ade0-20ca064224df)

**Comment by ulope** [comment]
I have the same issue and additionally for some reason only 3 ENRs are shown:
<img width="350" alt="image" src="https://github.com/dappnode/DAppNodePackage-holesky-obol/assets/55078/a8ab8154-cf90-46a5-b2fd-0a3311b51d45">

**Comment by dappnodedev** [comment]
This issue should be solved in the latest versions of the package. Please re-open the issue if you are still experiencing them
